apiVersion: v1
kind: Namespace
metadata:
  name: application

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: application
  labels:
    app: demo-app
spec:
  clusterIP: None   # Headless Service
  selector:
    app: demo-app
  ports:
    - port: 80
      name: http

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-app
  namespace: application
spec:
  serviceName: demo-app
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      nodeSelector:
        role: application   # 限制只能跑在 application node
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "application"
          effect: "NoSchedule"
      containers:
      - name: demo-app
        image: nginx:1.25
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app-hpa
  namespace: application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: demo-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # CPU 使用率 > 50% 時擴容